services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "4000:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=security
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345